## Linear algebra

In [28]:
import numpy as np
from scipy import linalg
from scipy import matmul

### a. Define a matrix A

In [17]:
A = np.array([ [1, 2, 3], [4, 5 ,6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### b. Define a vector b

In [18]:
b = np.array([1, 2, 3])
print(b)

[1 2 3]


### c. Solve the linear system of equations A x = b

In [11]:
x =  linalg.solve(A, b)
print(x)

[-0.23333333  0.46666667  0.1       ]


<ipython-input-11-e2ce7708f2ae>:1: LinAlgWarning: Ill-conditioned matrix (rcond=2.20282e-18): result may not be accurate.
  x =  linalg.solve(A, b)


### d. Check that your solution is correct by plugging it into the equation

In [29]:
matmul(A, x)

<ipython-input-29-af93bcfbe013>:1: DeprecationWarning: scipy.matmul is deprecated and will be removed in SciPy 2.0.0, use numpy.matmul instead
  matmul(A, x)


array([1., 2., 3.])

### e. Repeat steps a-d using a random 3x3 matrix B (instead of the vector b)

In [30]:
B = np.random.rand(3,3)
print(B)
X = linalg.solve(A, B)
print(matmul(A, X))

[[0.47258082 0.19334057 0.91306603]
 [0.00807576 0.57393061 0.47730198]
 [0.803761   0.37128565 0.67139385]]
[[ 0.5   0.    0.75]
 [ 5.    0.    1.5 ]
 [-0.5   0.    0.25]]


<ipython-input-30-7e37506a3085>:3: LinAlgWarning: Ill-conditioned matrix (rcond=2.20282e-18): result may not be accurate.
  X = linalg.solve(A, B)
<ipython-input-30-7e37506a3085>:4: DeprecationWarning: scipy.matmul is deprecated and will be removed in SciPy 2.0.0, use numpy.matmul instead
  print(matmul(A, X))


### f. Solve the eigenvalue problem for the matrix A and print the eigenvalues and eigenvectors

In [14]:
eig_values, eig_vectors = linalg.eig(A)
print(eig_values)
print(eig_vectors)

[ 1.61168440e+01+0.j -1.11684397e+00+0.j -9.75918483e-16+0.j]
[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


### g. Calculate the inverse, determinant of A

In [22]:
print(linalg.inv(A))
print(linalg.det(A))
print(linalg.det(linalg.inv(A)))

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]
0.0
0.024499999999999914


### h. Calculate the norm of A with different orders

In [23]:
print(linalg.norm(A))
print(linalg.norm(A, 1))
print(linalg.norm(A, 2))
print(linalg.norm(A, np.inf))
print(linalg.norm(A, -np.inf))

16.881943016134134
18.0
16.84810335261421
24.0
6.0
